KIND_EXE = "executable"
KIND_LIB = "library"
KIND_HEAD = "headers"
KIND_DEFAULT = KIND_EXE

STYLE_NICOLETTE = "nicolette"
STYLE_DEFAULT = STYLE_NICOLETTE

STANDARD_FOURTEEN = 14
STANDARD_SEVENTEEN = 17
STANDARD_DEFAULT = STANDARD_FOURTEEN

