KIND_EXE = "executable"
KIND_LIB = "library"
KIND_HEADER = "header"
KIND_DEFAULT = KIND_EXE
KIND = (KIND_EXE, KIND_LIB, KIND_HEADER)

STYLE_NICOLETTE = "nicolette"
STYLE_DEFAULT = STYLE_NICOLETTE
STYLE = (STYLE_NICOLETTE,)

STANDARD_FOURTEEN = 14
STANDARD_SEVENTEEN = 17
STANDARD_DEFAULT = STANDARD_FOURTEEN
STANDARD = (STANDARD_FOURTEEN, STANDARD_SEVENTEEN)

TESTING_CATCH2 = "catch2"
TESTING_DEFAULT = TESTING_CATCH2
TESTING = (TESTING_CATCH2,)
